- name: "St Theresa's Church"
  time: "2:30pm - 4:00pm"
  query: "St.+Theresa+Church,West+Roxbury+MA"
  description: " The wedding ceremony will be at the Hannon family church in West Roxbury, St. Theresa's, where Katie's parents and grandparents were married. The ceremony will be presided by Fr. Larry Brault."

- name: "Lakeview Pavilion"
  time: "5:00pm - 10:00pm"
  query: "Lakeview+Pavilion,Wrentham+MA"
  description: "The wedding reception will be hosted at the beautiful Lakeview Pavilion in Foxboro, Massachusetts, in the Lakeview Ballroom."

- name: "Hawthorn Suites"
  time: ""
  query: "Hawthorn+Suites+by+Wyndham+Franklin+%2F+Milford+Area"
  description: "Hotel accomendations will be at the Hawthorn Suites in Franklin, MA. A hotel block will be available until June 29th for a rate of $109, reference the Doherty/Buono block when booking."
